### ISSUE TITLE
Curl adapter seems to return the response

### ISSUE THREAD

**Issue by iammichiel** [widop/http-adapter#15]
When calling : (in geocoder BTW, bisous @egeloen)

```
$response = $this->httpAdapter->getContent($url);
```

This seems to return the content of the call. Shouldn't it be a wrapped HttpResponse?

**Comment by egeloen** [comment]
This repository is not used in geocoder... Can you elaborate?

**Comment by iammichiel** [comment]
Oops, wrong repo : talking about ivory-google-maps here. This line fails : https://github.com/egeloen/ivory-google-map/blob/master/src/Services/AbstractService.php#L259

```
call on non object.
```

With a little inspection, I found out there is no HttpResponse object used anywhere. The getContent calls returns a json-string with the response.

**Comment by egeloen** [comment]
What version of the library do you use?

**Comment by iammichiel** [comment]
```
"egeloen/google-map": "1.4.1",
"widop/http-adapter": "1.0.*",
```

**Comment by egeloen** [comment]
Upgrade this library to `~1.1` and everything should be fine

**Comment by iammichiel** [comment]
Indeed, fixed it. Thanks !
